apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog-container
        image: manasa44/book-catalog:latest
        ports:
        - containerPort: 8000  
        env:
        - name: DATABASE_URL
          value: "postgresql://task6_2_fjbo_user:nBzJsU5Rg6qtkHbd28OzAVLmGggvErOz@dpg-crhahhlsvqrc738ahjh0-a.oregon-postgres.render.com:5432/task6_2_fjbo"
        - name: APP_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8000  
      nodePort: 30001   